name: Selenium with TestNG - CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 20
      uses: actions/setup-java@v3
      with:
        java-version: '20'
        distribution: 'temurin'
        cache: maven
    - name: Install Google Chrome 

      run: |

              chmod +x ./script/InstallChrome.sh

                          ./script/InstallChrome.sh 
   
    - name: Build with Maven
      run: mvn -B clean test
